name: PureGym DWH Tag Deployment

on:
  workflow_dispatch:

permissions:
  contents: write  # Required to push tags

jobs:
  tag:
    name: Create and Push a Tag
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important to get all tags

      - name: Calculate next tag
        id: next
        run: |
          latest=$(git tag --sort=-v:refname | grep -E '^v?[0-9]+\.[0-9]+\.[0-9]+$' | head -n1 || echo "v0.0.0")
          echo "Latest tag: $latest"
          if [[ $latest =~ ^v?([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
            major=${BASH_REMATCH[1]}
            minor=${BASH_REMATCH[2]}
            patch=${BASH_REMATCH[3]}

            patch=$((patch + 1))
            if [[ $patch -ge 11 ]]; then
              patch=0
              minor=$((minor + 1))
            fi
            if [[ $minor -ge 11 ]]; then
              minor=0
              major=$((major + 1))
            fi

            next_tag="v$major.$minor.$patch"
          else
            next_tag="v1.0.0"
          fi

          echo "Next tag: $next_tag"
          echo "next_tag=$next_tag" >> $GITHUB_OUTPUT

      - name: Create and push tag
        run: |
          git tag ${{ steps.next.outputs.next_tag }}
          git push origin ${{ steps.next.outputs.next_tag }}